# This is the cmake config file for the Proper Motion Vectors plugin.
SET(PROPERMOTIONVECTORS_VERSION "${VERSION}")

ADD_DEFINITIONS(-DPROPERMOTIONVECTORS_PLUGIN_VERSION="${PROPERMOTIONVECTORS_VERSION}")
ADD_DEFINITIONS(-DPROPERMOTIONVECTORS_PLUGIN_LICENSE="GNU GPLv2 or later")

ADD_SUBDIRECTORY(src)
